import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John umeh",
      email: "a@a.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane umeh",
      email: "b@b.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 1,
      name: "iPhone 9",
      slug: "iPhone-9",
      description: "An apple mobile which is nothing like apple",
      price: 549,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      numReviews: 14,
      brand: "Apple",
      category: "smartphones",
      subcategory:"phone",
      image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 2,
      name: "iPhone X",
      slug: "iPhone-X",
      description:
        "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
      price: 899,
      discount: 12.96,
      isOffer: true,
      starRating: 2.69,
      countInStock: 94,
      numReviews: 14,
      brand: "Apple",
      category: "smartphones",
      
      image: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 3,
      name: "Samsung Universe 9",
      slug: "Samsung-Universe-9",
      description:
        "Samsung's new variant which goes beyond Galaxy to the Universe",
      price: 1249,
      discount: 12.96,
      isOffer: true,
      starRating: 1.69,
      countInStock: 94,
      brand: "Samsung",
      category: "smartphones",
      image: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 4,
      name: "OPPO F19",
      slug: "OPPO-F19",
      description: "OPPO F19 is officially announced on April 2021.",
      price: 280,
      discount: 12.96,
      isOffer: true,
      starRating: 3.69,
      countInStock: 94,
      brand: "OPPO",
      category: "smartphones",
      image: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 5,
      name: "Huawei P30",
      slug: "Huawei-P30",
      description:
        "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      price: 499,
      discount: 12.96,
      isOffer: true,
      starRating: 4.0,
      countInStock: 94,
      brand: "Huawei",
      category: "smartphones",
      image: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 6,
      name: "MacBook Pro",
      slug: "MacBook-Pro",
      description:
        "MacBook Pro 2021 with mini-LED display may launch between September, November",
      price: 1749,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      brand: "APPle",
      category: "laptops",
      image: "https://i.dummyjson.com/data/products/6/thumbnail.png",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 7,
      name: "Samsung Galaxy Book",
      slug: "Samsung-Galaxy-Book",
      description:
        "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
      price: 1499,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      brand: "Samsung",
      category: "laptops",
      image: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 8,
      name: "Microsoft Surface Laptop 4",
      slug: "Microsoft-Surface-Laptop-4",
      description:
        "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
      price: 1499,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      brand: "Microsoft Surface",
      category: "laptops",
      image: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 9,
      name: "Infinix INBOOK",
      slug: "Infinix-INBOOK",
      description:
        "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
      price: 1099,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      brand: "Infinix",
      category: "laptops",
      image: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 10,
      name: "HP Pavilion 15-DK1056WM",
      slug: "HP-Pavilion-15-DK1056WM",
      description:
        "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
      price: 1099,
      discount: 12.96,
      isOffer: true,
      starRating: 4.69,
      countInStock: 94,
      brand: "HP Pavilion",
      category: "laptops",
      image: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
  ],
};

export default data;
